time_step: 0.02
use_kalman: False
process_noise_covariance: 0.01
measurement_noise_covariance: 0.2

threshold: 0.0003 # threshold for small / large movement
scale: 12 # scale for relative position
clip_threshold: 0.1 # clip the relative position

ahead_time: 0.03
gain: 1000
ip_addr: "192.168.10.75"